name: 京东庄园

on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'
  watch:
    types: started
  repository_dispatch:
    types: gohomebeans

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【京东庄园】'
        run: |
          node JD_farm.js
        env:
          JDGH_XDZY_COOKIE: ${{ secrets.JDGH_XDZY_COOKIE }}
